collections:
  talks:
    output: true
    permalink: '/:name'
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
url: "http://trade-school.co"
baseurl: ""
title: "TRADE SCHOOL @ UNDERSTUDY | January 24-28, 2018 | Denver, CO"
description: "Five days of art and talks exploring the nature of work, set against the backdrop of North America’s largest gathering of outdoor industry leaders"
url: http://trade-school.co/
twitter:
  username: somethingindpnt
facebook:
  publisher: https://www.facebook.com/SomethingIndependent/
social:
  name: TRADE SCHOOL, a Something Independent project
  links:
    - https://twitter.com/somethingindpnt
    - https://www.facebook.com/SomethingIndependent/
    - https://www.instagram.com/somethingindependent/
logo: assets/trade-school-ig.png
defaults:
  - scope:
      path: ""
    values:
      image: assets/trade-school-ig.png
      last_modified_at: now
google_analytics: "UA-111929567-1"
future: true
