collections:
  talks:
    output: true
    permalink: '/:name'
plugins:
  - jekyll-seo-tag
title: "TRADE SCHOOL @ UNDERSTUDY | January 24-28, 2018 | Denver, CO"
google_analytics: "UA-111929567-1"
future: true
