# Global Options
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
future: true
permalink: pretty
google_analytics: "UA-111929567-2"
timezone: '-600'
# SEO / Sitemap
url: "http://thewright.co"
baseurl: ""
title: "The Wright | May 1-3, 2018 | Golden, CO"
description: "Three days to recognize, connect, and celebrate all those pursuing a passion, finding a purpose, exploring collaboration, and doing good work"
twitter:
  username: somethingindpnt
facebook:
  publisher: https://www.facebook.com/SomethingIndependent/
social:
  name: The Wright, a Something Independent project
  links:
    - https://twitter.com/somethingindpnt
    - https://www.facebook.com/SomethingIndependent/
    - https://www.instagram.com/somethingindependent/
logo: assets/the-wright-ig.jpg
# Collections
collections:
  events:
    output: true
defaults:
  - scope:
      path: ""
    values:
      image: assets/the-wright-ig.jpg
      last_modified_at: now
  - scope:
      path: ""
      type: events
    values:
      layout: events
prose:
  siteurl: 'http://thewright.co/'
  media: 'assets'
  ignore:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - CNAME
    - Rakefile
    - .travis.yml
    - _config.yml
    - _sass/
